### ISSUE TITLE
Images don't include CORS header

### ISSUE THREAD

**Issue by Grohden** [azrogers/ShibeOnline#1]
Hi, first of all, thanks for shibe online, I love it!

Second, while making a flutter app using CanvasKit I've stumbled across a CORS problem related to specifically the images served (request to the api itself has the proper header)

They don't contain the [Access-Control-Allow-Origin](https://docs.flutter.dev/development/platform-integration/web-images#host-your-images-in-a-cors-enabled-cdn) header, so I was wondering if it's possible to add this header for all image responses
![image](https://user-images.githubusercontent.com/7496871/168700554-b6b46e3e-c2f6-4f7e-9490-bf3c6138d6e6.png)
(no Access-Control-Allow-Origin header in the image)

**Comment by azrogers** [comment]
Added via NGINX, let me know if there's any issues.
